### ISSUE TITLE
The Java thread stack size specified is too small. Specify at least 448k

### ISSUE THREAD

**Issue by dyrnq** [dyrnq/JvmOptionsParser#1]
```bash
The Java thread stack size specified is too small. Specify at least 448k
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by dyrnq** [comment]
```bash
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:102)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:64)
	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:40)
Caused by: java.lang.OutOfMemoryError: Metaspace
```

**Comment by dyrnq** [comment]
before
```bash
    -XX:MetaspaceSize=20m
    -XX:MaxMetaspaceSize=20m
```
after
```bash
    -XX:MetaspaceSize=512m
    -XX:MaxMetaspaceSize=512m
```
